[FIX] utils: Fix "TypeError: expected string or bytes-like object, got 'NoneType'" (#128)
If the manifest file does not have version it raises the following TypeError

```python
from packaging.version import InvalidVersion, Version
Version({}.get("version"))
```

Error

    TypeError: expected string or bytes-like object, got 'NoneType'

Add TypeError to the except section in order to catch it