[FIX] utils: Fix "TypeError: expected string or bytes-like object, got 'NoneType'"
If the manifest file does not have version it raises the following TypeError

```python
from packaging.version import InvalidVersion, Version
Version({}.get("version"))
```

Error

    TypeError: expected string or bytes-like object, got 'NoneType'

Addng TypeError to except section in order to have catched